version: '3.2'

services:
    mymoney:
        build: ./
        container_name: mymoney
        ports:
            - 8000:5000
        volumes:
            - ./:/app/app/
        environment:
            - MONGODB_URI=mongodb://adminuser:verysecret@transactions_db/mymoney?authSource=admin
        depends_on:
            - transactions_db
            - transactions_db_test
    transactions_db:
        image: mongo
#        container_name: mongo
        ports:
            - 27117:27017
        volumes:
            - mymoney_db_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: adminuser
            MONGO_INITDB_ROOT_PASSWORD: verysecret

    transactions_db_test:
        image: mongo
        #container_name: mongo
        ports:
            - 27118:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: adminuser
            MONGO_INITDB_ROOT_PASSWORD: verysecret

    mongo-express:
        image: mongo-express
        ports:
            - 8081:8081
        environment:
            #ME_CONFIG_MONGODB_AUTH_DATABASE: mymoney
            ME_CONFIG_MONGODB_SERVER: transactions_db
            ME_CONFIG_MONGODB_ADMINUSERNAME: adminuser
            ME_CONFIG_MONGODB_ADMINPASSWORD: verysecret
        depends_on:
            - transactions_db

volumes:
    mymoney_db_data: